default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: slick_gifts_backend_development

test:
  <<: *default
  database: slick_gifts_backend_test

staging:
  <<: *default
  database: slick_gifts_backend_staging
  username: SlickGiftsBackend
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['POSTGRESQL_HOST'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
